[build]
  command = "ng build --configuration production && ng run VersoMart:serverless:production"
  publish = "dist/VersoMart/browser"

[[plugins]]
  package = "@netlify/plugin-angular-universal"
  [plugins.inputs]
    projectName = "VersoMart"
